import {
  MAGIC_BUBBLE_LEFT_FILL,
  MAGIC_BUBBLE_RIGHT_FILL,
  MAGIC_EMOJI_FALLBACK,
  PANEL_BORDER,
  TEXT_PRIMARY,
} from "@/constants/colors";
import {
  FONT_FAMILY_UI,
  FONT_SIZE_DIALOGUE_EMOJI_FALLBACK,
  FONT_SIZE_DIALOGUE_INLINE,
  FONT_SIZE_DIALOGUE_NAME,
  FONT_WEIGHT_TITLE,
  LINE_HEIGHT_DIALOGUE_INLINE,
} from "@/constants/typography";
import { TextStyle } from "pixi.js";

export const DIALOGUE_INLINE_STYLE = new TextStyle({
  fontFamily: FONT_FAMILY_UI,
  fontSize: FONT_SIZE_DIALOGUE_INLINE,
  fill: 0xfff1dd,
  lineHeight: LINE_HEIGHT_DIALOGUE_INLINE,
});

export const DIALOGUE_BODY_PAD_X = 88;
export const DIALOGUE_BODY_PAD_RIGHT = 14;
export const DIALOGUE_BODY_TOP_OFFSET = 44;
export const DIALOGUE_LINE_STRIDE = 26;
export const DIALOGUE_EMOJI_INLINE = 22;
export const DIALOGUE_EMOJI_GAP = 6;
export const DIALOGUE_BUBBLE_GAP_Y = 18;
export const DIALOGUE_BUBBLE_CORNER_RADIUS = 20;
export const DIALOGUE_BUBBLE_STROKE_WIDTH = 2;
export const DIALOGUE_BUBBLE_STROKE_ALPHA = 0.75;
export const DIALOGUE_BUBBLE_MIN_HEIGHT = 96;
export const DIALOGUE_BUBBLE_BODY_BOTTOM_PAD = 18;
export const DIALOGUE_BUBBLE_FILL_ALPHA = 0.96;
export const DIALOGUE_BUBBLE_MAX_TEXT_WIDTH = 640;
export const DIALOGUE_BUBBLE_SIDE_INSET = 32;
export const DIALOGUE_BUBBLE_EDGE_INSET = 8;
export const DIALOGUE_NAME_LABEL_X = DIALOGUE_BODY_PAD_X;
export const DIALOGUE_NAME_LABEL_Y = 12;
export const DIALOGUE_AVATAR_SIZE = 64;
export const DIALOGUE_AVATAR_X = 40;
export const DIALOGUE_AVATAR_Y_RATIO = 0.45;

export const DIALOGUE_NAME_STYLE = {
  fill: TEXT_PRIMARY,
  fontFamily: FONT_FAMILY_UI,
  fontSize: FONT_SIZE_DIALOGUE_NAME,
  fontWeight: FONT_WEIGHT_TITLE,
} as const;

export const DIALOGUE_EMOJI_FALLBACK_STYLE = {
  fontFamily: FONT_FAMILY_UI,
  fontSize: FONT_SIZE_DIALOGUE_EMOJI_FALLBACK,
  fill: MAGIC_EMOJI_FALLBACK,
} as const;

export const DIALOGUE_BUBBLE_STROKE_COLOR = PANEL_BORDER;
export const DIALOGUE_BUBBLE_FILL_LEFT = MAGIC_BUBBLE_LEFT_FILL;
export const DIALOGUE_BUBBLE_FILL_RIGHT = MAGIC_BUBBLE_RIGHT_FILL;
